# Generated by Django 5.2.5 on 2025-09-16 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('latitude', models.CharField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.CharField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('map_embed', models.TextField(blank=True, null=True, verbose_name='کد نقشه (iframe)')),
                ('google_maps_link', models.URLField(blank=True, null=True, verbose_name='لینک گوگل مپ')),
                ('balad_link', models.URLField(blank=True, null=True, verbose_name='لینک بلد')),
                ('neshan_link', models.URLField(blank=True, null=True, verbose_name='لینک نشان')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='دامنه سایت')),
                ('copy_rights', models.TextField(verbose_name='متن کپی رایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('site_logo', models.ImageField(upload_to='site_logo/images/', verbose_name='لوگو')),
                ('working_hours', models.CharField(blank=True, max_length=200, null=True, verbose_name='ساعات فعالیت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام')),
                ('subject', models.CharField(max_length=300, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='متن تماس با ما')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(blank=True, null=True, verbose_name='متن پاسخ تماس با ما')),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
