# Generated by Django 5.2.5 on 2025-09-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
