# Generated by Django 5.2.5 on 2025-09-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_sitesetting_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ساعات فعالیت'),
        ),
    ]
