# Generated by Django 5.2.5 on 2025-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_footerlinkbox_slider_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
