# Generated by Django 5.2.5 on 2025-09-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sitesetting_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='latitude',
            field=models.CharField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='longitude',
            field=models.CharField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
