# Generated by Django 5.2.5 on 2025-09-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_footerlink_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['order'], 'verbose_name': 'لینک فوتر', 'verbose_name_plural': 'لینک های فوتر'},
        ),
    ]
