# Generated by Django 5.2.5 on 2025-10-12 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_footerlink_create_date_footerlink_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام تماس با ما', 'verbose_name_plural': 'پیام\u200cهای تماس با ما'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='پاسخ داده شده'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='متن پاسخ'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
