# Generated by Django 5.2.5 on 2025-10-19 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته بندی')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LectureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='عنوان در URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان عکس')),
                ('image', models.ImageField(upload_to='gallery/images/', verbose_name='تصویر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='media_app.gallerycategory', verbose_name='بخش')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LectureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='عنوان در url')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_app.lecturecategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان سخنرانی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, unique=True, verbose_name='عنوان در url')),
                ('image', models.ImageField(upload_to='lectures/images/', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='lectures/videos/', verbose_name='فیلم سخنرانی')),
                ('audio', models.FileField(blank=True, null=True, upload_to='lectures/audios/', verbose_name='صوت سخنرانی')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدیو خارجی')),
                ('audio_url', models.URLField(blank=True, null=True, verbose_name='لینک صوت خارجی')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن سخنرانی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('published', 'منتشر شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سخنران')),
                ('selected_categories', models.ManyToManyField(related_name='lectures', to='media_app.lecturecategory', verbose_name='دسته بندی ها')),
                ('selected_tags', models.ManyToManyField(related_name='lectures', to='media_app.lecturetag', verbose_name='تگ ها')),
            ],
            options={
                'permissions': [('can_publish_lecture', 'Can publish lecture'), ('can_reject_lecture', 'Can reject lecture')],
            },
        ),
        migrations.CreateModel(
            name='LectureClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان کلیپ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, unique=True, verbose_name='عنوان در url')),
                ('video', models.FileField(blank=True, null=True, upload_to='lectures/videos/', verbose_name='فیلم کلیپ')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدیو خارجی')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='media_app.lecture', verbose_name='سخنرانی اصلی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LectureComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.lecture', verbose_name='سخنرانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_app.lecturecomment', verbose_name='والد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
