# Generated by Django 5.2.5 on 2025-10-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'permissions': [('publish_lecture', 'Can publish lecture'), ('reject_lecture', 'Can reject lecture')]},
        ),
    ]
