# Generated by Django 5.2.5 on 2025-09-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name': 'دسته بندی تصاویر', 'verbose_name_plural': 'دسته بندهای تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='دسته بندی'),
        ),
    ]
