# Generated by Django 5.2.5 on 2025-09-18 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_gallerycategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='عنوان در URL')),
            ],
            options={
                'verbose_name': 'تگ سخنرانی',
                'verbose_name_plural': 'تگ های سخنرانی',
            },
        ),
        migrations.CreateModel(
            name='LectureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='عنوان در url')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_app.lecturecategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی سخنرانی',
                'verbose_name_plural': 'دسته بندی های سخنرانی',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان سخنرانی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, unique=True, verbose_name='عنوان در url')),
                ('image', models.ImageField(upload_to='lectures/images/', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='lectures/videos/', verbose_name='فیلم سخنرانی')),
                ('audio', models.FileField(blank=True, null=True, upload_to='lectures/audios/', verbose_name='صوت سخنرانی')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدیو خارجی')),
                ('audio_url', models.URLField(blank=True, null=True, verbose_name='لینک صوت خارجی')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن سخنرانی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سخنران')),
                ('selected_categories', models.ManyToManyField(related_name='lectures', to='media_app.lecturecategory', verbose_name='دسته بندی ها')),
                ('selected_tags', models.ManyToManyField(related_name='lectures', to='media_app.lecturetag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'سخنرانی',
                'verbose_name_plural': 'سخنرانی ها',
            },
        ),
        migrations.CreateModel(
            name='LectureClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان کلیپ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, unique=True, verbose_name='عنوان در url')),
                ('video', models.FileField(blank=True, null=True, upload_to='lectures/videos/', verbose_name='فیلم کلیپ')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدیو خارجی')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='media_app.lecture', verbose_name='سخنرانی اصلی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LectureComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media_app.lecture', verbose_name='سخنرانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_app.lecturecomment', verbose_name='والد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر سخنرانی',
                'verbose_name_plural': 'نظرات سخنرانی',
            },
        ),
    ]
