# Generated by Django 5.2.5 on 2025-09-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_lecturetag_lecturecategory_lecture_lectureclip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectureclip',
            options={'verbose_name': 'کلیپ', 'verbose_name_plural': 'کلیپ ها'},
        ),
    ]
