# Generated by Django 5.2.5 on 2025-10-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_alter_lectureclip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('published', 'منتشر شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
    ]
