# Generated by Django 5.2.5 on 2025-10-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_lecture_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'permissions': [('can_publish_lecture', 'Can publish lecture'), ('can_reject_lecture', 'Can reject lecture')], 'verbose_name': 'سخنرانی', 'verbose_name_plural': 'سخنرانی ها'},
        ),
    ]
