# Generated by Django 5.2.5 on 2025-10-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0006_alter_lecture_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
