# Generated by Django 5.2.5 on 2025-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0007_lecturecomment_email_lecturecomment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecomment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده / نشده'),
        ),
    ]
