# Generated by Django 5.2.5 on 2025-10-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0008_lecturecomment_is_active_lecturecomment_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecomment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.lecture', verbose_name='سخنرانی'),
        ),
    ]
