# Generated by Django 5.2.5 on 2025-10-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('publish_article', 'Can publish article'), ('reject_article', 'Can reject article')]},
        ),
    ]
