# Generated by Django 5.2.5 on 2025-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_app/article_category/images', verbose_name='تصویر دسته بندی'),
        ),
    ]
