# Generated by Django 5.2.5 on 2025-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_articlecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('published', 'منتشر شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
    ]
