# Generated by Django 5.2.5 on 2025-10-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_article_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_publish_article', 'Can publish article'), ('can_reject_article', 'Can reject article')], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
