# Generated by Django 5.2.5 on 2025-10-12 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
