# Generated by Django 5.2.5 on 2025-10-12 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_articletag_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
