# Generated by Django 5.2.5 on 2025-10-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_articlecategory_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_publish_article', 'Can publish article'), ('can_reject_article', 'Can reject article')], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
